# Generated by Django 3.0.7 on 2020-06-11 00:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 0, 15, 19, 246881, tzinfo=utc)),
        ),
    ]
