# Generated by Django 3.0.7 on 2020-06-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20200611_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='Untitled-1.png', upload_to='post_img/'),
        ),
    ]
